baseURL = "/"
defaultContentLanguage = "cs"
defaultContentLanguageInSubdir = true
title = "ICT"
copyright = 'This work is licensed under a Creative Commons Attribution 4.0 International License.'

[author]
  email = 'TBA'
  name = 'Odborov치 organizace pracuj칤c칤ch v ICT'

[params]
  title = 'ICT'
  subTitle = 'Union'
  tagLine = 'Trade union of workers in <br> IT & communications.'
  joinCta = 'join us'
  support_email = 'ictodbory@gmail.com'
  support_phone = '+420 737 035 289'
  [params.legal]
    entityName = 'Odborov치 organizace pracuj칤c칤ch v ICT'
    entry = 'https://or.justice.cz/ias/ui/rejstrik-firma.vysledky?subjektId=1130032&typ=UPLNY'
    registrationNumber = '116 57 502'
  [params.social]
    github = 'https://github.com/ictunion'
    twitter = 'https://twitter.com/IctOdbory_Union'
    linkedin = 'http://www.linkedin.com/company/ictodbory-ictunion'
    facebook = 'https://www.facebook.com/ictodbory'
    youtube = ''
    mastodon = 'https://witter.cz/@ict_odbory_ict_union'
    instagram = 'https://www.instagram.com/ict_odbory_ict_union/'
  [params.navigation]
    home = "Home"
    aboutUs = "About Us"
    statutes = "Statutes"
    register = "Register"
    events = "Events"
    faq = "FAQ"
  [params.home]
    participateTitle = "How to participate?"
    membershipTitle = "Membership means..."
    eventsTitle = "Upcoming Events:"
  [params.footer]
    learnMore = "Learn More"
    socials = "Socials"
    languages = "Languages"
    legal = "Legal"
    legalLink = "ID"
    partners = "Parners"
    contacts = "Contacts"

[languages]
  [languages.cs]
    languageName = "캛esky"
    languageFlag = "游뻟릖"
    languagedirection = 'ltr'
    weight = 1
    [languages.cs.params]
      lang = 'cs'
      tagLine = 'Odborov치 organizace pracuj칤c칤ch v IT a komunikac칤ch.'
      joinCta = 'p콏idej se'
      [languages.cs.params.navigation]
        home = "Dom콢"
        aboutUs = "O n치s"
        statutes = "Stanovy"
        register = "Registrace"
        events = "Ud치losti"
        faq = "캛ast칠 dotazy"
      [languages.cs.params.home]
        participateTitle = "Jak se zapojit?"
        membershipTitle = "캛lenstv칤 ti p콏inese..."
        eventsTitle = "Pl치novan칠 ud치losti:"
      [languages.cs.params.footer]
        learnMore = "Poznej v칤ce"
        socials = "S칤t캩"
        languages = "Jazyky"
        legal = "Pr치vn칤 info"
        legalLink = "I캛O"
        partners = "Patne콏i"
        contacts = "Kontakty"

  [languages.en]
    languagedirection = 'ltr'
    languageName = "English"
    languageFlag = "游섫릖"
    weight = 2
    [languages.en.params]
      lang = "en"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[permalinks]
  events = '/:year/:slug/'
  registered = '/:slug'

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ['HTML'] # default is ['HTML','RSS'] - disable RSS for homepage
  page = ['HTML']

# Define list of partners
[[params.partners]]
  name = "OSPPP"
  link = "https://www.osppp.cz/"
[[params.partners]]
  name = "UNI Global Union"
  link = "https://uniglobalunion.org/"
