defaultContentLanguage = "cs"
defaultContentLanguageInSubdir = true
title = "ICT"
copyright = 'This work is licensed under a Creative Commons Attribution 4.0 International License.'

[author]
  email = 'ictodbory@gmail.com'
  name = 'Odborov치 organizace pracuj칤c칤ch v ICT'

[params]
  title = 'ICT'
  subTitle = 'Union'
  tagLine = 'Trade union of workers in IT & communications.'
  joinCta = 'join us'
  eventPosterAlt = 'Poster for the event'
  supportEmail = 'support@ictunion.cz'
  supportPhone = '+420 737 035 289'
  publicUrl = 'https://ictunion.cz'
  [params.legal]
    entityName = 'Odborov치 organizace pracuj칤c칤ch v ICT'
    entry = 'https://or.justice.cz/ias/ui/rejstrik-firma.vysledky?subjektId=1130032&typ=UPLNY'
    registrationNumber = '116 57 502'
  [params.social]
    github = 'https://github.com/ictunion'
    twitter = 'https://twitter.com/IctOdbory_Union'
    linkedin = 'http://www.linkedin.com/company/ictodbory-ictunion'
    facebook = 'https://www.facebook.com/ictodbory'
    youtube = ''
    mastodon = 'https://witter.cz/@ict_odbory_ict_union'
    instagram = 'https://www.instagram.com/ict_odbory_ict_union/'
  [params.navigation]
    home = "Home"
    aboutUs = "About Us"
    statutes = "Statutes"
    register = "Application"
    events = "Events"
    workplaces = "Workplaces"
    faq = "FAQ"
    statements = "Statements"
    career = "Career"
  [params.home]
    participateTitle = "How to participate?"
    membershipTitle = "We provide..."
    eventsTitle = "Upcoming Events:"
  [params.footer]
    learnMore = "Learn More"
    socials = "Socials"
    languages = "Languages"
    legal = "Legal"
    legalLink = "ID"
    partners = "Partners"
    contacts = "Contacts"
    licensingNote = '''
    Content is provided under <a target="_blank" href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International</a>.<br>
    Source code is <a target="_blank" href="https://github.com/ictunion/main-website-public">released</a> under <a target="_blank" href="//www.gnu.org/licenses/agpl-3.0.html">AGPL</a> license.
    '''

[languages]
  [languages.cs]
    languagedirection = 'ltr'
    weight = 1
    [languages.cs.params]
      subTitle = 'Odbory'
      lang = 'cs'
      language = '캛esky'
      languageFlag = "游뻟릖"
      tagLine = 'Odborov치 organizace pracuj칤c칤ch v IT a komunikac칤ch.'
      joinCta = 'p콏idej se'
      eventPosterAlt = 'Plak치t k akci'
      [languages.cs.params.navigation]
        home = "Dom콢"
        aboutUs = "O n치s"
        statutes = "Stanovy"
        register = "P콏ihl치코ka"
        events = "Akce"
        workplaces = "Pracovi코t캩"
        faq = "캛ast칠 dotazy"
        statements = "Prohl치코en칤"
        career = "Career"
      [languages.cs.params.home]
        participateTitle = "Jak se zapojit?"
        membershipTitle = "캛lenstv칤 ti p콏inese..."
        eventsTitle = "Pl치novan칠 akce:"
      [languages.cs.params.footer]
        learnMore = "Poznej v칤ce"
        socials = "S칤t캩"
        languages = "Jazyky"
        legal = "Pr치vn칤 info"
        legalLink = "I캛O"
        partners = "Partne콏i"
        contacts = "Kontakty"
        licensingNote = '''
        Obsah poskytujeme pod licenc칤 <a target="_blank" href="https://creativecommons.org/licenses/by/4.0/deed.cs">Creative Commons Attribution 4.0 International</a>.<br>
        Zdrojov칳 k칩d <a target="_blank" href="https://github.com/ictunion/main-website-public">je vyd치n</a> pod licenc칤 <a target="_blank" href="//www.gnu.org/licenses/agpl-3.0.html">AGPL</a>.
        '''

  [languages.en]
    languagedirection = 'ltr'
    weight = 2
    [languages.en.params]
      lang = "en"
      language = 'English'
      languageFlag = "游섫릖"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[permalinks]
  events = '/events/:year/:slug/'
  registered = '/:slug'
  workplaces = '/workplace/:slug/'
  statements = '/statements/:slug/'
  career = '/career/:slug/'

[languages.cs.permalinks]
  events = '/akce/:year/:slug/'
  workplaces = '/pracoviste/:slug/'
  statements = '/prohlaseni/:slug/'
  career = '/career/:slug/'

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ['HTML'] # default is ['HTML','RSS'] - disable RSS for homepage
  page = ['HTML']

# Define list of partners
[[params.partners]]
  name = "OSPPP"
  link = "https://www.osppp.cz/"
[[params.partners]]
  name = "UNI Global Union"
  link = "https://www.uni-europa.org/sectors/ict-related-services/"
