baseURL = "/"
defaultContentLanguage = "cs"
defaultContentLanguageInSubdir = true
title = "ICT"

[languages]
  [languages.cs]
    languageName = "ÄŒesky"
    languageFlag = "ğŸ‡¨ğŸ‡¿"
    languagedirection = 'ltr'
    weight = 1
    [languages.cs.params]
      lang = 'cs'
      tagLine = 'OdborovÃ¡ organizace pracujÃ­cÃ­ch v <br> IT a komunikacÃ­ch.'
      joinCta = 'pÅ™idej se'
      [languages.cs.params.navigation]
        home = "DomÅ¯"
        aboutUs = "O nÃ¡s"
        statutes = "Stanovy"
        register = "Registrace"
        events = "UdÃ¡losti"
        faq = "ÄŒastÃ© Dotazy"
      [languages.cs.params.home]
        participateTitle = "Jak se zapojit?"
        membershipTitle = "ÄŒlenstvÃ­ ti pÅ™inese..."
        eventsTitle = "PlÃ¡novanÃ© UdÃ¡losti:"
      [langauges.cs.params.footer]
        learnMore = "Poznat VÃ­ce"
        socials = "SÃ­tÄ›"
        languages = "Jazyky"
        legal = "PrÃ¡vnÃ­ info"
        legalNote = "registered in ..."
        legalLink = "RegistraÄnÃ­ ZÃ¡znam"

  [languages.en]
    languagedirection = 'ltr'
    languageName = "English"
    languageFlag = "ğŸ‡¬ğŸ‡§"
    weight = 2
    [languages.en.params]
      lang = "en"

[params]
  title = 'ICT'
  subTitle = 'Union'
  tagLine = 'Trade union of workers in <br> IT & communications.'
  joinCta = 'join us'
  [params.navigation]
    home = "Home"
    aboutUs = "About Us"
    statutes = "Statutes"
    register = "Register"
    events = "Events"
    faq = "FAQ"
  [params.home]
    participateTitle = "How to participate?"
    membershipTitle = "Membership means..."
    eventsTitle = "Upcoming Events:"
  [params.footer]
    learnMore = "Learn More"
    socials = "Socials"
    languages = "Languages"
    legal = "Legal"
    legalNote = "registered in ..."
    legalLink = "Legal Record"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
